# Generated by Django 4.2 on 2024-03-18 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=130)),
                ('last_name', models.CharField(max_length=130)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=230)),
                ('vat', models.CharField(max_length=30)),
                ('text', tinymce.models.HTMLField(blank=True, verbose_name='Hakemusteksti')),
                ('sended', models.DateTimeField(auto_now_add=True, verbose_name='Hakemus lähetetty')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Päivitetty')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
