# Generated by Django 4.2 on 2024-03-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyapplication',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
