# Generated by Django 4.2 on 2024-03-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0002_companyapplication_terms_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyapplication',
            name='invoicing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyapplication',
            name='position',
            field=models.CharField(default='', max_length=130),
        ),
        migrations.AddField(
            model_name='companyapplication',
            name='reseller',
            field=models.BooleanField(default=False),
        ),
    ]
