# Generated by Django 4.1 on 2024-03-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0003_companyapplication_invoicing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyapplication',
            name='bill_address',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Laskutusosoite'),
        ),
        migrations.AddField(
            model_name='companyapplication',
            name='bill_city',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Postitoimipaikka'),
        ),
        migrations.AddField(
            model_name='companyapplication',
            name='bill_postal',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Postinumero'),
        ),
        migrations.AddField(
            model_name='companyapplication',
            name='phone',
            field=models.CharField(default='', max_length=130, verbose_name='Puhelinnumero'),
        ),
        migrations.AddField(
            model_name='companyapplication',
            name='status',
            field=models.CharField(choices=[('new', 'Uusi'), ('accepted', 'Hyväksytty'), ('canceled', 'Hylätty')], default='new', max_length=20, verbose_name='Tila'),
        ),
        migrations.AlterField(
            model_name='companyapplication',
            name='company',
            field=models.CharField(max_length=230, verbose_name='Yritys'),
        ),
        migrations.AlterField(
            model_name='companyapplication',
            name='first_name',
            field=models.CharField(max_length=130, verbose_name='Etunimi'),
        ),
        migrations.AlterField(
            model_name='companyapplication',
            name='invoicing',
            field=models.BooleanField(default=False, verbose_name='Laskutus'),
        ),
        migrations.AlterField(
            model_name='companyapplication',
            name='last_name',
            field=models.CharField(max_length=130, verbose_name='Sukunimi'),
        ),
        migrations.AlterField(
            model_name='companyapplication',
            name='position',
            field=models.CharField(default='', max_length=130, verbose_name='Asema yrityksessä'),
        ),
        migrations.AlterField(
            model_name='companyapplication',
            name='reseller',
            field=models.BooleanField(default=False, verbose_name='Jälleenmyynti'),
        ),
        migrations.AlterField(
            model_name='companyapplication',
            name='sended',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Hakemus jätetty'),
        ),
        migrations.AlterField(
            model_name='companyapplication',
            name='terms_accepted',
            field=models.BooleanField(default=False, verbose_name='Ehdot hyväksytty'),
        ),
        migrations.AlterField(
            model_name='companyapplication',
            name='vat',
            field=models.CharField(max_length=30, verbose_name='Y-tunnus'),
        ),
    ]
