# Generated by Django 4.1 on 2024-04-02 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0004_companyapplication_bill_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyapplication',
            options={'verbose_name': 'B2B hakemus', 'verbose_name_plural': 'B2B hakemukset'},
        ),
    ]
