# Generated by Codex on 2026-09-01

import decimal
import re

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def seed_duca_di_venezia_calculator(apps, schema_editor):
    Product = apps.get_model('shop', 'Product')
    Variant = apps.get_model('shop', 'Variant')
    Package = apps.get_model('shop', 'ProductMaterialCalculatorPackage')

    product = Product.objects.filter(pk=1295).first()
    if not product:
        return

    product.material_calculator_manual_enabled = True
    product.material_calculator_coverage_min = decimal.Decimal('12')
    product.material_calculator_coverage_max = decimal.Decimal('14')
    product.material_calculator_unit = 'm2_per_l'
    product.save(update_fields=[
        'material_calculator_manual_enabled',
        'material_calculator_coverage_min',
        'material_calculator_coverage_max',
        'material_calculator_unit',
    ])

    amount_pattern = re.compile(r'(?P<amount>\d+(?:[,.]\d+)?)\s*(?P<unit>kg|l)\b', re.I)
    variants = Variant.objects.filter(product_id=product.id, active=True).order_by('item_code', 'size', 'id')
    order = 0
    seen_packages = set()
    for variant in variants:
        label_source = ' '.join(
            str(value or '') for value in (variant.size, variant.item_description)
        ).strip()
        match = amount_pattern.search(label_source)
        if not match:
            continue

        amount = decimal.Decimal(match.group('amount').replace(',', '.'))
        unit = match.group('unit').lower()
        if unit != 'l':
            continue

        package_key = (amount, unit)
        if package_key in seen_packages:
            continue
        seen_packages.add(package_key)

        order += 1
        Package.objects.create(
            product_id=product.id,
            variant_id=variant.id,
            active=True,
            label=(variant.size or f'{amount.normalize()} {unit}').strip(),
            amount=amount,
            unit=unit,
            order=order,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0060_attribute_a_class_en_attribute_a_class_fi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='material_calculator_coverage_max',
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(decimal.Decimal('0.001'))],
                verbose_name='Riittoisuus / menekki max',
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='material_calculator_coverage_min',
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(decimal.Decimal('0.001'))],
                verbose_name='Riittoisuus / menekki min',
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='material_calculator_manual_enabled',
            field=models.BooleanField(
                default=False,
                help_text='Käytä alla olevia tuotekohtaisia arvoja automaattisen laskennan sijaan.',
                verbose_name='Muokkaa menekkilaskuria käsin',
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='material_calculator_unit',
            field=models.CharField(
                blank=True,
                choices=[
                    ('m2_per_l', 'm²/l'),
                    ('m2_per_kg', 'm²/kg'),
                    ('l_per_m2', 'l/m²'),
                    ('kg_per_m2', 'kg/m²'),
                ],
                default='',
                max_length=12,
                verbose_name='Riittoisuuden yksikkö',
            ),
        ),
        migrations.CreateModel(
            name='ProductMaterialCalculatorPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Mukana laskurissa')),
                ('label', models.CharField(
                    blank=True,
                    default='',
                    help_text='Esimerkiksi 0,75 l, 2,5 l tai 20 kg. Jos tyhjä, käytetään määrää ja yksikköä.',
                    max_length=100,
                    verbose_name='Pakkauskoko / näytettävä teksti',
                )),
                ('amount', models.DecimalField(
                    decimal_places=3,
                    max_digits=8,
                    validators=[django.core.validators.MinValueValidator(decimal.Decimal('0.001'))],
                    verbose_name='Tuotteen määrä pakkauksessa',
                )),
                ('unit', models.CharField(
                    choices=[('l', 'l'), ('kg', 'kg')],
                    max_length=2,
                    verbose_name='Pakkausyksikkö',
                )),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Järjestys')),
                ('product', models.ForeignKey(
                    db_constraint=False,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='material_calculator_packages',
                    to='shop.product',
                    verbose_name='Tuote',
                )),
                ('variant', models.ForeignKey(
                    db_constraint=False,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='material_calculator_packages',
                    to='shop.variant',
                    verbose_name='Laskennassa mukana oleva tuotevaihtoehto',
                )),
            ],
            options={
                'verbose_name': 'Menekkilaskurin pakkaus',
                'verbose_name_plural': 'Menekkilaskurin pakkaukset',
                'ordering': ('order', 'amount', 'id'),
            },
        ),
        migrations.RunPython(seed_duca_di_venezia_calculator, migrations.RunPython.noop),
    ]
