# Generated by Django 5.1.4 on 2026-01-16 12:58

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('content', tinymce.models.HTMLField(verbose_name='Sisältö')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services_images/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='services_images/thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Palvelu',
                'verbose_name_plural': 'Palvelut',
            },
        ),
    ]
