# Generated by Django 5.1.4 on 2026-01-16 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nimi')),
                ('email', models.EmailField(max_length=254, verbose_name='Sähköposti')),
                ('phone', models.CharField(max_length=20, verbose_name='Puhelin')),
                ('message', models.TextField(verbose_name='Viesti')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Luotu')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_requests', to='services.service', verbose_name='Palvelu')),
            ],
            options={
                'verbose_name': 'Tarjouspyyntö',
                'verbose_name_plural': 'Tarjouspyynnöt',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequestFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='quote_requests/', verbose_name='Tiedosto')),
                ('quote_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='services.quoterequest')),
            ],
        ),
    ]
