# Generated by Django 5.1.4 on 2026-02-01 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_quoterequest_quoterequestfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAdditionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services_images/additional/')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='services.service')),
            ],
        ),
    ]
