# Generated by Django 5.1.4 on 2026-02-01 13:25

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0059_alter_variant_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('content', tinymce.models.HTMLField(verbose_name='Sisältö')),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses_images/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses_images/thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='courses', to='shop.category', verbose_name='Tuotekategoriat')),
            ],
            options={
                'verbose_name': 'Kurssi',
                'verbose_name_plural': 'Kurssit',
            },
        ),
        migrations.CreateModel(
            name='CourseAdditionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses_images/additional/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nimi')),
                ('email', models.EmailField(max_length=254, verbose_name='Sähköposti')),
                ('phone', models.CharField(max_length=20, verbose_name='Puhelin')),
                ('message', models.TextField(verbose_name='Viesti')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Luotu')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='courses.course', verbose_name='Kurssi')),
            ],
            options={
                'verbose_name': 'Kurssi-ilmoittautuminen',
                'verbose_name_plural': 'Kurssi-ilmoittautumiset',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseRegistrationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='course_registrations/', verbose_name='Tiedosto')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='courses.courseregistration')),
            ],
        ),
    ]
