# Generated by Django 4.1 on 2024-03-01 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_image_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grain', models.CharField(blank=True, default='', max_length=2)),
                ('family', models.CharField(blank=True, default='', max_length=200)),
                ('purpose', models.CharField(blank=True, default='', max_length=200)),
                ('application', models.CharField(blank=True, default='', max_length=200)),
                ('color', models.CharField(blank=True, default='', max_length=200)),
                ('gloss', models.CharField(blank=True, default='', max_length=200)),
                ('sufficiency', models.CharField(blank=True, default='', max_length=200)),
                ('voc', models.CharField(blank=True, default='', max_length=200)),
                ('thinning', models.CharField(blank=True, default='', max_length=200)),
                ('density', models.CharField(blank=True, default='', max_length=200)),
                ('a_class', models.CharField(blank=True, default='', max_length=200)),
                ('epd', models.CharField(blank=True, default='', max_length=200)),
                ('ch2o', models.CharField(blank=True, default='', max_length=200)),
                ('haccp', models.CharField(blank=True, default='', max_length=200)),
                ('method', models.CharField(blank=True, default='', max_length=200)),
                ('primer', models.CharField(blank=True, default='', max_length=200)),
                ('ph', models.CharField(blank=True, default='', max_length=200)),
                ('abrasion_class', models.CharField(blank=True, default='', max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='shop.product')),
            ],
        ),
    ]
