# Generated by Django 4.1 on 2024-03-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='color_thumbnails/'),
        ),
    ]
