# Generated by Django 4.1 on 2024-03-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_storesettings_store_name_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='photo',
        ),
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rating_photos/'),
        ),
        migrations.AddField(
            model_name='review',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='rating_thumbnails/'),
        ),
    ]
