# Generated by Django 4.1 on 2024-03-16 13:18

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_recentproductview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storesettings',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='storesettings',
            name='store_name',
        ),
        migrations.AddField(
            model_name='storesettings',
            name='terms',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Käyttöehdot'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
