# Generated by Django 4.1 on 2024-03-16 18:30

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_storesettings_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='properties',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tech_info',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='open_time',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Aukioloajat'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=200),
        ),
    ]
