# Generated by Django 4.1 on 2024-03-18 10:41

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_review_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='company_terms',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Myyntiehdot yrityksille'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='email',
            field=models.EmailField(blank=True, help_text='Tähän sähköpostiin lähtee kaikki kaupan ilmoitukset.', max_length=254),
        ),
    ]
