# Generated by Django 4.1 on 2024-03-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_storesettings_company_terms_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Tuotekategoria', 'verbose_name_plural': 'Tuotekategoriat'},
        ),
        migrations.AlterModelOptions(
            name='variant',
            options={'verbose_name': 'Variantti', 'verbose_name_plural': 'Variantit'},
        ),
        migrations.AddField(
            model_name='variant',
            name='order_item',
            field=models.BooleanField(default=False, verbose_name='Tilaustuote'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktiivinen'),
        ),
    ]
