# Generated by Django 4.1 on 2024-04-02 06:53

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_category_options_alter_variant_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'verbose_name': 'Ominaisuus', 'verbose_name_plural': 'Ominaisuudet'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Yhteydenotto'},
        ),
        migrations.AlterModelOptions(
            name='groupsettings',
            options={'verbose_name': 'Ryhmä', 'verbose_name_plural': 'Ryhmät'},
        ),
        migrations.AlterModelOptions(
            name='multiplier',
            options={'verbose_name': 'Kerroin', 'verbose_name_plural': 'Kertoimet'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'Tuote', 'verbose_name_plural': 'Tuotteet'},
        ),
        migrations.AlterModelOptions(
            name='recentproductview',
            options={'ordering': ['-viewed_at'], 'verbose_name': 'Viimeksi katsottu', 'verbose_name_plural': 'Viimeksi katsotut'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Arvostelu', 'verbose_name_plural': 'Arvostelut'},
        ),
        migrations.AlterModelOptions(
            name='shippingcost',
            options={'verbose_name': 'Toimitus', 'verbose_name_plural': 'Toimitusmaksut'},
        ),
        migrations.AlterModelOptions(
            name='storesettings',
            options={'verbose_name': 'Kaupan asetukset', 'verbose_name_plural': 'Kaupan asetukset'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tagit'},
        ),
        migrations.AlterModelOptions(
            name='tax',
            options={'verbose_name': 'Vero', 'verbose_name_plural': 'Verot'},
        ),
        migrations.AlterModelOptions(
            name='variant',
            options={'verbose_name': 'Tuotevaihtoehto', 'verbose_name_plural': 'Tuotevaihtoehdot'},
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='category_images'),
        ),
    ]
