# Generated by Django 4.1 on 2024-04-03 13:56

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_attribute_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='bg_image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.AddField(
            model_name='category',
            name='info',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='properties',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='tech_info',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='company_terms',
            field=tinymce.models.HTMLField(blank=True, default='', verbose_name='Myyntiehdot yrityksille'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='open_time',
            field=tinymce.models.HTMLField(blank=True, default='', verbose_name='Aukioloajat'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='terms',
            field=tinymce.models.HTMLField(blank=True, default='', verbose_name='Käyttöehdot'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='base',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='variant',
            name='cat_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='variant',
            name='color',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='variant',
            name='customs_code',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='gloss',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='variant',
            name='grain',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='variant',
            name='item_code',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='item_description',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='variant',
            name='size',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='variant',
            name='weight',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10, null=True),
        ),
    ]
