# Generated by Django 4.1 on 2024-04-03 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_rename_image_category_bg_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='grain',
            field=models.CharField(blank=True, db_index=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='variant',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
