# Generated by Django 4.1 on 2024-04-05 09:29

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_variant_grain_alter_variant_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Aktiivinen')),
                ('title', tinymce.models.HTMLField(default='', verbose_name='Otsikko')),
                ('info', tinymce.models.HTMLField(blank=True, default='', verbose_name='Teksti')),
                ('link_text', models.CharField(blank=True, default='', max_length=200, verbose_name='Linkin teksti')),
                ('link', models.URLField(blank=True, verbose_name='Linkki')),
                ('bg_image', models.ImageField(blank=True, upload_to='slider_images', verbose_name='Taustakuva')),
            ],
            options={
                'verbose_name': 'Kuvaesitys',
                'verbose_name_plural': 'Kuvaesitykset',
            },
        ),
    ]
