# Generated by Django 4.1 on 2024-04-05 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_slider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='bg_image',
            new_name='image',
        ),
    ]
