# Generated by Django 4.1 on 2024-04-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_rename_bg_image_slider_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['order'], 'verbose_name': 'Kuvaesitys', 'verbose_name_plural': 'Kuvaesitykset'},
        ),
        migrations.AddField(
            model_name='slider',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Järjestys'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='info',
            field=models.TextField(blank=True, verbose_name='Teksti'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Otsikko'),
        ),
    ]
