# Generated by Django 4.1 on 2024-04-07 17:32

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_alter_slider_options_slider_order_alter_slider_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='info',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Teksti'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=tinymce.models.HTMLField(max_length=100, verbose_name='Otsikko'),
        ),
    ]
