# Generated by Django 4.1 on 2024-04-09 18:05

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_slider_info_alter_slider_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='info',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
    ]
