# Generated by Django 4.1 on 2024-04-09 19:34

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_tag_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=tinymce.models.HTMLField(max_length=100, verbose_name='Nimi'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=tinymce.models.HTMLField(max_length=100, verbose_name='Nimi'),
        ),
    ]
