# Generated by Django 4.1 on 2024-04-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_alter_category_name_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='info',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tag',
            name='info',
            field=models.TextField(blank=True, default=''),
        ),
    ]
