# Generated by Django 4.1 on 2024-04-10 08:06

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_alter_category_info_alter_tag_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='top_bar',
            field=tinymce.models.HTMLField(blank=True, default='', verbose_name='Tärkeä tieto / Yläpalkki'),
        ),
    ]
