# Generated by Django 4.1 on 2024-04-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_storesettings_top_bar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AlterField(
            model_name='category',
            name='bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images'),
        ),
    ]
