# Generated by Django 4.1 on 2024-04-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_remove_product_stock_alter_category_bg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='customs_code',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
