# Generated by Django 4.1 on 2024-04-18 19:58

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_alter_variant_customs_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='info_fi',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Teksti'),
        ),
        migrations.AddField(
            model_name='slider',
            name='info_sv',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Teksti'),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_fi',
            field=tinymce.models.HTMLField(max_length=100, null=True, verbose_name='Otsikko'),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_sv',
            field=tinymce.models.HTMLField(max_length=100, null=True, verbose_name='Otsikko'),
        ),
    ]
