# Generated by Django 4.1 on 2024-05-03 08:10

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_slider_info_fi_slider_info_sv_slider_title_fi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=tinymce.models.HTMLField(verbose_name='Otsikko'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title_fi',
            field=tinymce.models.HTMLField(null=True, verbose_name='Otsikko'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title_sv',
            field=tinymce.models.HTMLField(null=True, verbose_name='Otsikko'),
        ),
        migrations.CreateModel(
            name='ProductYoutubeLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Videon nimi')),
                ('youtube_link', models.URLField(verbose_name='YouTube linkki')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_links', to='shop.product')),
            ],
            options={
                'verbose_name': 'Videolinkki',
                'verbose_name_plural': 'Videolinkit',
            },
        ),
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Tiedoston nimi')),
                ('document', models.FileField(upload_to='product_documents/', verbose_name='Tiedosto')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='shop.product')),
            ],
            options={
                'verbose_name': 'PDF Tiedosto',
                'verbose_name_plural': 'PDF Tiedostot',
            },
        ),
    ]
