# Generated by Django 4.1 on 2024-05-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_alter_slider_title_alter_slider_title_fi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productyoutubelink',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Videon nimi'),
        ),
        migrations.AlterField(
            model_name='productyoutubelink',
            name='youtube_link',
            field=models.CharField(default='', max_length=255, verbose_name='YouTube linkki'),
        ),
    ]
