# Generated by Django 4.1 on 2024-05-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_alter_productyoutubelink_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Koodi')),
                ('discount', models.IntegerField(blank=True, verbose_name='Alennusprosentti')),
                ('free_shipping', models.BooleanField(default=False, verbose_name='Ilmainen toimitus')),
            ],
        ),
        migrations.AlterField(
            model_name='productyoutubelink',
            name='youtube_link',
            field=models.CharField(default='', max_length=255, verbose_name='YouTube koodi ilman https://youtu.be/'),
        ),
    ]
