# Generated by Django 4.1 on 2024-05-30 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_coupon_alter_productyoutubelink_youtube_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'Kuponki', 'verbose_name_plural': 'Kupongit'},
        ),
    ]
