# Generated by Django 4.1 on 2024-06-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_coupon_amount_alter_coupon_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='min_purchase',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Minimiostos'),
        ),
    ]
