# Generated by Django 5.1.4 on 2024-12-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_coupon_min_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products_many', to='shop.category'),
        ),
    ]
