# Generated by Django 5.1.4 on 2024-12-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_remove_product_categories_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='keyword',
            field=models.TextField(blank=True, default='', help_text='Pilkuilla erotetut avainsanat'),
        ),
    ]
