# Generated by Django 5.1.4 on 2024-12-13 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_category_keyword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='keyword',
            new_name='keywords',
        ),
    ]
