# Generated by Django 5.1.4 on 2024-12-13 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_rename_keyword_category_keywords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='keywords',
            new_name='keyword',
        ),
    ]
