# Generated by Django 5.1.4 on 2024-12-16 21:56

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_rename_keywords_category_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='info',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
    ]
