# Generated by Django 5.1.4 on 2024-12-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0047_alter_category_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.TextField(blank=True, default=''),
        ),
    ]
