# Generated by Django 5.1.4 on 2025-01-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0048_category_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceUpdateFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='price_updates/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hintojen päivitys',
                'verbose_name_plural': 'Hintojen päivitys',
                'ordering': ['id'],
            },
        ),
    ]
