# Generated by Django 5.1.4 on 2025-02-26 19:59

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0050_product_discount_percentage_alter_product_multiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='lft',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='rght',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='tree_id',
            field=models.IntegerField(default=0),
        ),
    ]
