# Generated by Django 5.1.4 on 2025-04-05 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0052_alter_category_level_alter_category_lft_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='effects_photos/', verbose_name='Photo')),
                ('application_method', models.CharField(max_length=255, verbose_name='Application Method')),
                ('coverage', models.CharField(max_length=50, verbose_name='Coverage')),
                ('tools_base', models.CharField(max_length=255, verbose_name='Tools for Base Coat')),
                ('tools_finish', models.CharField(max_length=255, verbose_name='Tools for Finish')),
                ('dilution', models.CharField(max_length=100, verbose_name='Dilution')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effects', to='shop.product')),
            ],
            options={
                'verbose_name': 'Efekti',
                'verbose_name_plural': 'Efektit',
            },
        ),
    ]
