# Generated by Django 5.1.4 on 2025-05-03 18:13

import django.db.models.deletion
import mptt.fields
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0053_effect'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='invert_colors',
            field=models.BooleanField(default=False, verbose_name='Käännä värit'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='single_use',
            field=models.BooleanField(default=False, verbose_name='Kertakäyttöinen'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='used_by',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Käyttäjät jotka ovat käyttäneet'),
        ),
        migrations.AddField(
            model_name='effect',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Nimi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktiivinen'),
        ),
        migrations.AlterField(
            model_name='category',
            name='bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images', verbose_name='Taustakuva'),
        ),
        migrations.AlterField(
            model_name='category',
            name='info',
            field=tinymce.models.HTMLField(blank=True, default='', verbose_name='Teksti'),
        ),
        migrations.AlterField(
            model_name='category',
            name='keyword',
            field=models.TextField(blank=True, default='', help_text='Pilkuilla erotetut avainsanat', verbose_name='Avainsanat'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=200, verbose_name='Nimi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.category', verbose_name='Yläkategoria'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.TextField(blank=True, default='', verbose_name='Otsikko'),
        ),
        migrations.AlterField(
            model_name='effect',
            name='application_method',
            field=models.CharField(max_length=255, verbose_name='Käyttöohjeet'),
        ),
        migrations.AlterField(
            model_name='effect',
            name='coverage',
            field=models.CharField(max_length=50, verbose_name='Peittoala m²/l'),
        ),
        migrations.AlterField(
            model_name='effect',
            name='dilution',
            field=models.CharField(max_length=100, verbose_name='Laimennus'),
        ),
        migrations.AlterField(
            model_name='effect',
            name='photo',
            field=models.ImageField(upload_to='effects_photos/', verbose_name='Kuva'),
        ),
        migrations.AlterField(
            model_name='effect',
            name='tools_base',
            field=models.CharField(max_length=255, verbose_name='Työkalut peruskerrokseen'),
        ),
        migrations.AlterField(
            model_name='effect',
            name='tools_finish',
            field=models.CharField(max_length=255, verbose_name='Työkalut viimeistelykerrokseen'),
        ),
    ]
