# Generated by Django 5.1.4 on 2025-10-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0054_category_invert_colors_coupon_single_use_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='used_by_anonymous',
            field=models.BooleanField(default=False, verbose_name='Käytetty anonyymisti'),
        ),
    ]
