# Generated by Django 5.1.4 on 2025-10-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0055_coupon_used_by_anonymous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='color',
        ),
        migrations.AddField(
            model_name='product',
            name='palette_priority',
            field=models.CharField(choices=[('color2', 'Color2 ensin'), ('color1', 'Color1 ensin')], default='color2', help_text='Miten paletit näytetään asiakkaille', max_length=10, verbose_name='Palettien prioriteetti'),
        ),
        migrations.AddField(
            model_name='product',
            name='use_color1_palette',
            field=models.BooleanField(default=False, help_text='Näytä perinteiset värit kuvilla', verbose_name='Käytä Color1-palettia'),
        ),
        migrations.AddField(
            model_name='product',
            name='use_color2_palette',
            field=models.BooleanField(default=True, help_text='Näytä uudet värit RGB-arvoilla', verbose_name='Käytä Color2-palettia'),
        ),
        migrations.AddField(
            model_name='variant',
            name='b',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Blue component (0–255)', null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='color1',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Traditional color with image files', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='color2',
            field=models.CharField(blank=True, db_index=True, default='', help_text='New color with RGB values', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='g',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Green component (0–255)', null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='hue',
            field=models.FloatField(blank=True, help_text='Hue value (0–360 degrees)', null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='r',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Red component (0–255)', null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='size',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='color_thumbnails/'),
        ),
    ]
