# Generated by Django 5.1.4 on 2025-10-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0056_remove_variant_color_product_palette_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='free_shipping_method',
            field=models.CharField(choices=[('postnord_lokero', 'Postnord Lokero'), ('postnord_kotiinkuljetus', 'Postnord Kotiinkuljetus'), ('both', 'Molemmat Postnord-toimitukset')], default='postnord_lokero', max_length=40, verbose_name='Ilmainen toimitus menetelmä'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='free_shipping_threshold',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10, verbose_name='Ilmaisen toimituksen kynnys'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='pickup_enabled',
            field=models.BooleanField(default=True, verbose_name='Nouto myymälästä käytössä'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='postnord_kotiinkuljetus_enabled',
            field=models.BooleanField(default=True, verbose_name='Postnord Kotiinkuljetus käytössä'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='postnord_kotiinkuljetus_price',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=10, verbose_name='Postnord Kotiinkuljetus hinta'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='postnord_lokero_enabled',
            field=models.BooleanField(default=True, verbose_name='Postnord Lokero käytössä'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='postnord_lokero_price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10, verbose_name='Postnord Lokero hinta'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='weight_based_enabled',
            field=models.BooleanField(default=True, verbose_name='Painoperusteinen toimitus käytössä'),
        ),
    ]
