# Generated by Django 5.1.4 on 2025-10-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0057_storesettings_free_shipping_method_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variant',
            options={'verbose_name': 'Product variant', 'verbose_name_plural': 'Product variants'},
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='free_shipping_method',
            field=models.CharField(choices=[('postnord_lokero', 'Postnord palvelupiste'), ('postnord_kotiinkuljetus', 'Postnord Kotiinkuljetus'), ('both', 'Molemmat Postnord-toimitukset')], default='postnord_lokero', max_length=40, verbose_name='Ilmainen toimitus menetelmä'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='postnord_lokero_enabled',
            field=models.BooleanField(default=True, verbose_name='Postnord palvelupiste käytössä'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='postnord_lokero_price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10, verbose_name='Postnord palvelupiste hinta'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='order_item',
            field=models.BooleanField(default=False, verbose_name='Order product'),
        ),
    ]
