# Generated by Django 5.1.4 on 2026-01-16 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0058_alter_variant_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variant',
            options={'verbose_name': 'Tuotevaihtoehto', 'verbose_name_plural': 'Tuotevaihtoehdot'},
        ),
    ]
