# Generated by Django 4.1 on 2024-02-18 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('processing', 'Käsittelyssä'), ('shipped', 'Lähetetty'), ('delivered', 'Toimitettu'), ('canceled', 'Peruttu')], default='processing', max_length=20, verbose_name='Tila')),
                ('first_name', models.CharField(max_length=50, verbose_name='Etunimi')),
                ('last_name', models.CharField(max_length=50, verbose_name='Sukunimi')),
                ('email', models.EmailField(max_length=50, verbose_name='Sähköposti')),
                ('address', models.CharField(max_length=250, verbose_name='Osoite')),
                ('postal', models.CharField(max_length=20, verbose_name='Postinumero')),
                ('city', models.CharField(max_length=100, verbose_name='Postitoimipaikka')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='Puhelinnumero')),
                ('bill_address', models.CharField(blank=True, max_length=250, verbose_name='Laskutus osoite')),
                ('bill_postal', models.CharField(blank=True, max_length=20, verbose_name='Laskutus postinumero')),
                ('bill_city', models.CharField(blank=True, max_length=100, verbose_name='Laskutus postitoimipaikka')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Tehty')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Päivitetty')),
                ('notes', models.TextField(blank=True, max_length=200, null=True, verbose_name='Muistiinpanot')),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('delivery_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('payed', models.BooleanField(default=False, verbose_name='Maksettu')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.BigIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('color', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('grain', models.CharField(blank=True, max_length=2, null=True)),
                ('gloss', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
            ],
        ),
    ]
