# Generated by Django 4.1 on 2024-03-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Uusi'), ('processing', 'Käsittelyssä'), ('shipped', 'Lähetetty'), ('canceled', 'Peruttu')], default='new', max_length=20, verbose_name='Tila'),
        ),
    ]
