# Generated by Django 4.1 on 2024-04-02 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name': 'Tilaus', 'verbose_name_plural': 'Tilaukset'},
        ),
    ]
