# Generated by Django 5.1.4 on 2025-10-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='b',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Blue component (0–255)', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='color_type',
            field=models.CharField(blank=True, help_text='Color palette type: color1 or color2', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='g',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Green component (0–255)', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='r',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Red component (0–255)', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='thumbnail_url',
            field=models.CharField(blank=True, help_text='Thumbnail URL for color1', max_length=500, null=True),
        ),
    ]
