# Generated by Django 5.1.4 on 2025-10-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_orderitem_b_orderitem_color_type_orderitem_g_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Verkkomaksu'), ('cod', 'Maksaa noudettaessa')], default='online', max_length=20, verbose_name='Maksutapa'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('pickup', 'Nouto myymälästä'), ('weight_based', 'Painoperusteinen toimitus'), ('postnord_lokero', 'Postnord Lokero'), ('postnord_kotiinkuljetus', 'Postnord Kotiinkuljetus')], default='weight_based', max_length=30, verbose_name='Toimitustapa'),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Välisumma'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Loppusumma'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Toimitusmaksu'),
        ),
    ]
