# Generated by Django 5.1.4 on 2025-10-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_payment_method_order_shipping_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('pickup', 'Nouto myymälästä'), ('weight_based', 'Painoperusteinen toimitus'), ('postnord_lokero', 'Postnord palvelupiste'), ('postnord_kotiinkuljetus', 'Postnord Kotiinkuljetus')], default='weight_based', max_length=30, verbose_name='Toimitustapa'),
        ),
    ]
